services:
  nginx:
    image: nginx:stable-bookworm
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: php-container
    expose:
      - "9000"
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db

  frontend:
    build: 
      context: .
      dockerfile: ./docker/client/Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    working_dir: /app
    command: npm run start
    depends_on:
      - php
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todos
      MYSQL_USER: ryuta
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/db/my.conf:/etc/mysql/conf.d/my.cnf

volumes:
  dbdata:

